SELECT TOP 10 * FROM dbo.customer_data;
--Q1. What is  the total revenue generated by male vs female customers

SELECT 
    gender,
    SUM([purchase_amount_(usd)]) AS total_revenue
FROM 
    customer_data
GROUP BY 
    gender;
---Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT 
customer_id,
[purchase_amount_(usd)]
FROM
customer_data 
WHERE discount_applied ='Yes' and [purchase_amount_(usd)] >= (select AVG([purchase_amount_(usd)]) from customer_data)
